name = "my-worker"
type = "webpack"
account_id = "39fdea6111845004992c5b75fc1d21b4"
workers_dev = true
route = ""
zone_id = ""
[vars]
  # From your spreadsheet URL: docs.google.com/spreadsheets/d/DOC_ID/...
  DOC_ID = "1o0kd1EYGP3tnJb1BSYCZKHUkpKnGPhm5n2B14G5sEzw"
  # Name of spreadsheet tab to get data from
  SHEET_NAME = "mangaapi"
  # Seconds to cache data
  TTL = "5"
